### PR TITLE
Update debug target for DLL and Plugins project to run from install

### PR DESCRIPTION
**Pull request by Holt59**

### CODE REVIEW

**Comment by isanae** [comment]
This has a duplicate of `set_project_to_run_from_install()` in `exe.cmake`, right?

**Comment by Holt59** [comment]
The `set_project_to_run_from_install` uses `${output_name}` but I don't think it's available in `dll.cmake` or `plugin.cmake`. I used hard-coded `ModOrganizer.exe`.

**Comment by isanae** [comment]
Then I'd make `set_project_to_run_from_install()` take a parameter for that.

**Comment by isanae** [comment]
What if I want to run a batch file?

;)

**Pull request merged**
